version: '3.7'

services:
  database:
    image: postgres
    container_name: pg-docker
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=peloton_db
    ports:
    - "5432:5432"
    restart: always

  backend:
      container_name: peloton-backend
      build: 
        context: .
        dockerfile: Dockerfile
      command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 3001 --reload
      ports:
      - "3001:3001"
      volumes: 
        - ./app:/app/app:cached
      depends_on:
        - database

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
    - "5050:80"
    depends_on:
      - database