version: '3.7'

services: 
  backend:
      container_name: peloton-backend
      build: 
        context: .
        dockerfile: Dockerfile
      command: uvicorn main:app --reload
      volumes: 
        - ./app:/app/:cached