version: '3.7'

services: 
  backend:
      container_name: peloton-backend
      build: 
        context: .
        dockerfile: Dockerfile
      command: uvicorn app.main:app --host 0.0.0.0 --port 3001 --reload
      ports:
      - "3001:3001"
      volumes: 
        - ./app:/app/app:cached