version: '3.8'

services:
    peloton_db:
        container_name: peloton_db
        hostname: peloton_db
        image: postgres:alpine
        ports:
            - "54321:5432"
        restart: unless-stopped
        env_file:
            - dbcredentials.env
        volumes:
          - ./pgdata:/var/lib/postgresql/data